main: dk.muj.derius.perm.DeriusPerm
name: Derius-Perm
version: 0.1_dev
#website: http://muj.dk/Derius/Mining
authors: [Madus, Ulumulu1510]
description: <e>Permissions for everything related to Derius.
depend: [Derius-Core]
load: startup
